### PR TITLE
Complete the removal of Python bindings from the PDAL main library.

### PR DESCRIPTION
**Pull request by hobu**
See https://github.com/PDAL/PDAL/pull/2895 for details.

### CODE REVIEW

**Comment by jrobichaud** [comment]
Just a little note regarding this.

PDAL/pdal:latest no longer have python support since the removal was merged in PDAL/pdal docker.

People will have to fallback to an older version of PDAL until this is merged and released on Pypi.

**Comment by jrobichaud** [comment]
I did some tests on this merge request and it works well.

It fixes the problem "filters.python" was only available in the version of python used when pdal was compiled. It was very limiting. We could not create virtual environments or use another version of python.

👍

**Comment by hobu** [comment]
I still have some issues on the build_ext so it doesn't rebuild the plugins every invocation and installation of the embedded plugins to do yet.

**Comment by jrobichaud** [comment]
Just wondering, did you test/cover the case someone could use an older version of pdal with "filters.python" still bundled in it?

**Comment by hobu** [comment]
> Just wondering, did you test/cover the case someone could use an older version of pdal with "filters.python" still bundled in it?

No, I didn't test for that scenario. This installation would simply clobber it as currently implemented.

**Pull request merged**
